{"version":3,"sources":["webpack:///./src/pages/error.vue?9b01","webpack:///src/pages/error.vue","webpack:///./src/pages/error.vue?f3b6","webpack:///./src/pages/error.vue"],"names":["render","_vm","this","_h","$createElement","_c","_self","hasRenderError","_v","on","refresh","attrs","throwError","_s","obj","a","staticRenderFns","data","mounted","Error","methods","component"],"mappings":"yHAAA,IAAIA,EAAS,WAAa,IAAIC,EAAIC,KAASC,EAAGF,EAAIG,eAAmBC,EAAGJ,EAAIK,MAAMD,IAAIF,EAAG,OAASF,EAAIM,eAA8KF,EAAG,MAAM,CAACA,EAAG,IAAI,CAACJ,EAAIO,GAAG,aAAaH,EAAG,WAAW,CAACI,GAAG,CAAC,MAAQR,EAAIS,UAAU,CAACT,EAAIO,GAAG,WAAW,GAAhQH,EAAG,MAAM,CAACA,EAAG,UAAU,CAACM,MAAM,CAAC,YAAc,WAAWN,EAAG,WAAW,CAACI,GAAG,CAAC,MAAQR,EAAIW,aAAa,CAACX,EAAIO,GAAG,UAAUH,EAAG,IAAI,CAACJ,EAAIO,GAAGP,EAAIY,GAAGZ,EAAIa,IAAIC,OAAO,IAC7QC,EAAkB,GCetB,GACEC,KADF,WAEI,MAAO,CACLV,gBAAgB,IAIpBW,QAPF,WAQI,MAAM,IAAIC,MAAM,kCAElBC,QAAS,CACPR,WADJ,WAEM,MAAM,IAAIO,MAAM,oCAElBT,QAJJ,WAMMR,KAAKY,IAAM,CAAjB,OACMZ,KAAKK,gBAAiB,KCjCmT,I,YCO3Uc,EAAY,eACd,EACArB,EACAgB,GACA,EACA,KACA,KACA,MAIa,aAAAK,E","file":"assets/js/chunk-2d0d3720.fe81596b.js","sourcesContent":["var render = function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return (!_vm.hasRenderError)?_c('div',[_c('a-empty',{attrs:{\"description\":\"这是错误页\"}}),_c('a-button',{on:{\"click\":_vm.throwError}},[_vm._v(\"抛个异常\")]),_c('p',[_vm._v(_vm._s(_vm.obj.a))])],1):_c('div',[_c('p',[_vm._v(\"页面渲染失败啦\")]),_c('a-button',{on:{\"click\":_vm.refresh}},[_vm._v(\"刷新试试\")])],1)}\nvar staticRenderFns = []\n\nexport { render, staticRenderFns }","<template>\r\n  <!-- 正常渲染就展示以下内容 -->\r\n  <div v-if=\"!hasRenderError\">\r\n    <a-empty description=\"这是错误页\" />\r\n    <a-button @click=\"throwError\">抛个异常</a-button>\r\n    <!-- 在 render 中出现异常的话也能被 Vue.config.errorHandler 方法捕获到，但也会导致页面渲染失败。比如下面尝试使用未定义的 obj 的 a 属性就会出现异常 -->\r\n    <p>{{ obj.a }}</p>\r\n  </div>\r\n  <!-- 如果渲染异常了，就展示下面的内容 -->\r\n  <div v-else>\r\n    <p>页面渲染失败啦</p>\r\n    <a-button @click=\"refresh\">刷新试试</a-button>\r\n  </div>\r\n</template>\r\n\r\n<script>\r\nexport default {\r\n  data() {\r\n    return {\r\n      hasRenderError: false,\r\n    }\r\n  },\r\n  // 无论是在生命周期函数还是在自定义事件中抛出异常，都会被 Vue.config.errorHandler 方法捕获到，且不会影响页面的正常渲染\r\n  mounted() {\r\n    throw new Error('抛出一个自定义错误：mounted。但不影响页面正常渲染。')\r\n  },\r\n  methods: {\r\n    throwError() {\r\n      throw new Error('抛出一个自定义错误：throwError。但不影响页面正常渲染')\r\n    },\r\n    refresh() {\r\n      // 这里通过新增 obj 并将 hasRenderError 设置为 false 来消除渲染异常\r\n      this.obj = { a: 'a' }\r\n      this.hasRenderError = false\r\n    },\r\n  },\r\n}\r\n</script>\r\n","import mod from \"-!../../node_modules/cache-loader/dist/cjs.js??ref--13-0!../../node_modules/thread-loader/dist/cjs.js!../../node_modules/babel-loader/lib/index.js!../../node_modules/cache-loader/dist/cjs.js??ref--1-0!../../node_modules/vue-loader/lib/index.js??vue-loader-options!./error.vue?vue&type=script&lang=js&\"; export default mod; export * from \"-!../../node_modules/cache-loader/dist/cjs.js??ref--13-0!../../node_modules/thread-loader/dist/cjs.js!../../node_modules/babel-loader/lib/index.js!../../node_modules/cache-loader/dist/cjs.js??ref--1-0!../../node_modules/vue-loader/lib/index.js??vue-loader-options!./error.vue?vue&type=script&lang=js&\"","import { render, staticRenderFns } from \"./error.vue?vue&type=template&id=0d6aa970&\"\nimport script from \"./error.vue?vue&type=script&lang=js&\"\nexport * from \"./error.vue?vue&type=script&lang=js&\"\n\n\n/* normalize component */\nimport normalizer from \"!../../node_modules/vue-loader/lib/runtime/componentNormalizer.js\"\nvar component = normalizer(\n  script,\n  render,\n  staticRenderFns,\n  false,\n  null,\n  null,\n  null\n  \n)\n\nexport default component.exports"],"sourceRoot":""}